"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/client";

type Profile = { id:string; display_name:string; phone:string|null; area:string; avatar_url:string|null; completed_deals:number; no_shows:number; created_at:string };
type Media = { id:string; public_url:string; sort_order:number };
type Listing = { id:string; seller_id:string; title:string; description:string; price:number; category:string; condition:string; negotiable:boolean; area:string; visibility_radius_km:number; status:string; created_at:string; listing_media:Media[]; seller:Profile };
type Offer = { id:string; listing_id:string; buyer_id:string; amount:number; attempt_number:number; status:string; created_at:string; listing:{title:string;price:number}; buyer:Profile };
type Deal = { id:string; listing_id:string; buyer_id:string; seller_id:string; final_price:number; status:string; created_at:string; listing:{title:string;listing_media:Media[]}; buyer:Profile; seller:Profile; cod_schedules:Array<{id:string;proposed_by:string;scheduled_at:string;location_name:string;location_address:string;notes:string|null;status:string}>; deal_confirmations:Array<{user_id:string}> };

const supabase = createClient();
const categories = ["Elektronik","Komputer","Fashion","Furnitur","Rumah","Hobi","Otomotif","Usaha","Produk Lokal","Lainnya"];
const conditions = ["Baru","Seperti baru","Bekas baik","Bekas"];
const rupiah = (value:number) => `Rp${new Intl.NumberFormat("id-ID").format(value)}`;
const dateTime = (value:string) => new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Makassar"}).format(new Date(value));

function Icon({name,size=20}:{name:string;size?:number}) {
  const paths:Record<string,React.ReactNode>={search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,plus:<><circle cx="12" cy="12" r="9"/><path d="M8 12h8M12 8v8"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,close:<><path d="m6 6 12 12M18 6 6 18"/></>,shield:<><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></>,check:<path d="m5 12 4 4L19 6"/>,logout:<><path d="M10 17l5-5-5-5M15 12H3"/><path d="M14 3h7v18h-7"/></>,down:<path d="m7 10 5 5 5-5"/>,upload:<><path d="M12 16V4m0 0L7 9m5-5 5 5"/><path d="M5 15v5h14v-5"/></>};
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function CustomSelect({name,options,defaultValue}:{name:string;options:Array<{value:string;label:string}>;defaultValue:string}){
  const [value,setValue]=useState(defaultValue); const [open,setOpen]=useState(false); const current=options.find(option=>option.value===value)?.label||value;
  return <div className={`custom-select ${open?"open":""}`} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setOpen(false)}}><input type="hidden" name={name} value={value}/><button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}><span>{current}</span><Icon name="down" size={17}/></button>{open&&<div className="select-menu" role="listbox">{options.map(option=><button type="button" role="option" aria-selected={value===option.value} className={value===option.value?"selected":""} key={option.value} onClick={()=>{setValue(option.value);setOpen(false)}}>{option.label}{value===option.value&&<Icon name="check" size={16}/>}</button>)}</div>}</div>;
}

function FilePicker(){const [name,setName]=useState("");return <label className="file-picker"><span>Foto barang</span><input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required onChange={event=>setName(event.target.files?.[0]?.name||"")}/><span className="file-control"><span className="file-icon"><Icon name="upload"/></span><span><strong>{name||"Pilih foto barang"}</strong><small>{name?"Klik untuk mengganti foto":"JPG, PNG, atau WebP · maksimal 5 MB"}</small></span></span></label>}

function ToggleField({name,label}:{name:string;label:string}){const [enabled,setEnabled]=useState(true);return <div className="toggle-field"><input type="hidden" name={name} value={enabled?"on":""}/><button type="button" role="switch" aria-checked={enabled} className={enabled?"on":""} onClick={()=>setEnabled(!enabled)}><i/></button><span>{label}</span></div>}

export default function Home(){
  const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<Profile|null>(null);
  const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [authMode,setAuthMode]=useState<"login"|"register">("login");
  const [listings,setListings]=useState<Listing[]>([]); const [offers,setOffers]=useState<Offer[]>([]); const [deals,setDeals]=useState<Deal[]>([]);
  const [tab,setTab]=useState<"home"|"sell"|"activity"|"profile">("home"); const [query,setQuery]=useState(""); const [category,setCategory]=useState("Semua");
  const [selected,setSelected]=useState<Listing|null>(null); const [offerAmount,setOfferAmount]=useState(""); const [submitting,setSubmitting]=useState(false);

  const loadData=useCallback(async(currentUser:User,currentProfile:Profile)=>{
    const [listingResult,offerResult,dealResult]=await Promise.all([
      supabase.from("listings").select("*,listing_media(*),seller:profiles!listings_seller_id_fkey(*)").order("created_at",{ascending:false}),
      supabase.from("offers").select("id,listing_id,buyer_id,amount,attempt_number,status,created_at,listing:listings!offers_listing_id_fkey(title,price),buyer:profiles!offers_buyer_id_fkey(*)").eq("seller_id",currentUser.id).eq("status","pending").order("created_at",{ascending:false}),
      supabase.from("deals").select("id,listing_id,buyer_id,seller_id,final_price,status,created_at,listing:listings!deals_listing_id_fkey(title,listing_media(*)),buyer:profiles!deals_buyer_id_fkey(*),seller:profiles!deals_seller_id_fkey(*),cod_schedules(*),deal_confirmations(user_id)").or(`buyer_id.eq.${currentUser.id},seller_id.eq.${currentUser.id}`).order("created_at",{ascending:false})
    ]);
    if(listingResult.error) setError(listingResult.error.message); else setListings((listingResult.data||[]) as unknown as Listing[]);
    if(!offerResult.error) setOffers((offerResult.data||[]) as unknown as Offer[]);
    if(!dealResult.error) setDeals((dealResult.data||[]) as unknown as Deal[]);
    setProfile(currentProfile);
  },[]);

  const bootstrap=useCallback(async()=>{
    setLoading(true); const {data:{user:currentUser}}=await supabase.auth.getUser(); setUser(currentUser);
    if(currentUser){ const {data}=await supabase.from("profiles").select("*").eq("id",currentUser.id).maybeSingle(); if(data) await loadData(currentUser,data as Profile); }
    setLoading(false);
  },[loadData]);

  useEffect(()=>{const timer=setTimeout(()=>void bootstrap(),0); const {data}=supabase.auth.onAuthStateChange(()=>void bootstrap()); return()=>{clearTimeout(timer);data.subscription.unsubscribe()};},[bootstrap]);
  useEffect(()=>{if(!user)return; const channel=supabase.channel(`codkan-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"offers"},()=>profile&&loadData(user,profile)).on("postgres_changes",{event:"*",schema:"public",table:"deals"},()=>profile&&loadData(user,profile)).subscribe(); return()=>{supabase.removeChannel(channel)};},[user,profile,loadData]);

  const visible=useMemo(()=>listings.filter(l=>(category==="Semua"||l.category===category)&&(`${l.title} ${l.description}`.toLowerCase().includes(query.toLowerCase()))),[listings,category,query]);
  const clear=()=>{setError("");setMessage("")};

  async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();clear();setSubmitting(true);const form=new FormData(e.currentTarget);const email=String(form.get("email"));const password=String(form.get("password"));const result=authMode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});setSubmitting(false);if(result.error)setError(result.error.message);else if(authMode==="register"&&!result.data.session)setMessage("Akun dibuat. Periksa email untuk konfirmasi, lalu masuk.");}
  async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user)return;clear();setSubmitting(true);const form=new FormData(e.currentTarget);const payload={id:user.id,display_name:String(form.get("name")),phone:String(form.get("phone"))||null,area:String(form.get("area"))};const {data,error:err}=await supabase.from("profiles").insert(payload).select().single();setSubmitting(false);if(err)setError(err.message);else await loadData(user,data as Profile);}
  async function createListing(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user||!profile)return;clear();setSubmitting(true);const form=new FormData(e.currentTarget);const file=form.get("photo") as File;const id=crypto.randomUUID();const payload={id,seller_id:user.id,title:String(form.get("title")),description:String(form.get("description")),price:Number(String(form.get("price")).replace(/\D/g,"")),category:String(form.get("category")),condition:String(form.get("condition")),negotiable:form.get("negotiable")==="on",area:profile.area,visibility_radius_km:Number(form.get("radius")),status:"draft"};
    const created=await supabase.from("listings").insert(payload).select().single();if(created.error){setSubmitting(false);setError(created.error.message);return}
    const safeName=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,"-");const path=`${user.id}/${id}/${Date.now()}-${safeName}`;const uploaded=await supabase.storage.from("listing-media").upload(path,file,{contentType:file.type,upsert:false});
    if(uploaded.error){await supabase.from("listings").delete().eq("id",id);setSubmitting(false);setError(uploaded.error.message);return}
    const publicUrl=supabase.storage.from("listing-media").getPublicUrl(path).data.publicUrl;const media=await supabase.from("listing_media").insert({listing_id:id,storage_path:path,public_url:publicUrl});
    if(media.error){setSubmitting(false);setError(media.error.message);return}await supabase.from("listings").update({status:"active"}).eq("id",id);setSubmitting(false);setMessage("Barang berhasil dipasang.");setTab("home");await loadData(user,profile);}
  async function submitOffer(){if(!selected||!offerAmount)return;clear();setSubmitting(true);const {error:err}=await supabase.rpc("submit_offer",{p_listing_id:selected.id,p_amount:Number(offerAmount.replace(/\D/g,""))});setSubmitting(false);if(err)setError(err.message);else{setMessage("Tawaran terkirim ke penjual.");setSelected(null);setOfferAmount("");if(user&&profile)await loadData(user,profile)}}
  async function respond(offerId:string,action:"accept"|"reject"){clear();setSubmitting(true);const {error:err}=await supabase.rpc("respond_offer",{p_offer_id:offerId,p_action:action,p_counter_amount:null});setSubmitting(false);if(err)setError(err.message);else{setMessage(action==="accept"?"Tawaran diterima. Deal Room dibuat.":"Tawaran ditolak.");if(user&&profile)await loadData(user,profile)}}
  async function proposeSchedule(e:FormEvent<HTMLFormElement>,dealId:string){e.preventDefault();clear();const form=new FormData(e.currentTarget);const raw=String(form.get("scheduled_at"));const match=raw.match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2})$/);if(!match){setError("Gunakan format jadwal DD/MM/YYYY HH:mm.");return}const [,day,month,year,hour,minute]=match;const scheduled=new Date(`${year}-${month}-${day}T${hour}:${minute}:00+08:00`);if(Number.isNaN(scheduled.getTime())){setError("Tanggal atau waktu tidak valid.");return}setSubmitting(true);const {error:err}=await supabase.rpc("propose_cod_schedule",{p_deal_id:dealId,p_scheduled_at:scheduled.toISOString(),p_location_name:String(form.get("location_name")),p_location_address:String(form.get("location_address")),p_notes:String(form.get("notes"))||null});setSubmitting(false);if(err)setError(err.message);else if(user&&profile)await loadData(user,profile)}
  async function acceptSchedule(dealId:string){setSubmitting(true);const {error:err}=await supabase.rpc("accept_cod_schedule",{p_deal_id:dealId});setSubmitting(false);if(err)setError(err.message);else if(user&&profile)await loadData(user,profile)}
  async function confirmDeal(dealId:string){setSubmitting(true);const {data,error:err}=await supabase.rpc("confirm_deal_completion",{p_deal_id:dealId});setSubmitting(false);if(err)setError(err.message);else{setMessage(data==="completed"?"COD selesai dan reputasi diperbarui.":"Konfirmasi tersimpan. Menunggu pihak lain.");if(user&&profile)await loadData(user,profile)}}

  if(loading)return <main className="center"><div className="loader"/><p>Menyiapkan CODkan…</p></main>;
  if(!user)return <main className="auth-page"><section className="auth-brand"><a className="brand">COD<span>kan</span></a><h1>Ketemu.<br/>Tawar. <em>Deal.</em></h1><p>Marketplace lokal untuk transaksi langsung dan bayar saat barang sudah diperiksa.</p><div><Icon name="shield"/><span><strong>COD saja</strong><small>Tanpa transfer, wallet, atau pembayaran dalam aplikasi.</small></span></div></section><form className="auth-card" onSubmit={authenticate}><p>MULAI DI PASAR LOKALMU</p><h2>{authMode==="login"?"Masuk ke CODkan":"Buat akun"}</h2><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Kata sandi<input name="password" type="password" minLength={8} autoComplete={authMode==="login"?"current-password":"new-password"} required/></label>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<button className="primary" disabled={submitting}>{submitting?"Memproses…":authMode==="login"?"Masuk":"Daftar"}</button><button className="text-button" type="button" onClick={()=>{clear();setAuthMode(authMode==="login"?"register":"login")}}>{authMode==="login"?"Belum punya akun? Daftar":"Sudah punya akun? Masuk"}</button></form></main>;
  if(!profile)return <main className="onboarding"><form onSubmit={saveProfile}><a className="brand">COD<span>kan</span></a><p>LANGKAH TERAKHIR</p><h1>Atur pasar lokalmu</h1><span>Area menentukan barang yang bisa kamu lihat dan tawar.</span><label>Nama tampilan<input name="name" minLength={2} required/></label><label>Nomor telepon <small>(terbuka hanya setelah deal)</small><input name="phone" type="tel"/></label><label>Area domisili<input name="area" placeholder="Contoh: Somba Opu, Gowa" minLength={2} required/></label>{error&&<div className="alert error">{error}</div>}<button className="primary" disabled={submitting}>Simpan dan mulai</button></form></main>;

  return <main className="app">
    <header><div className="header-inner"><button className="brand plain" onClick={()=>setTab("home")}>COD<span>kan</span></button><button className="area"><Icon name="pin"/><span><small>Area aktif</small><strong>{profile.area}</strong></span></button><div className="header-search"><Icon name="search"/><input aria-label="Cari barang" placeholder="Cari barang di sekitar…" value={query} onChange={e=>setQuery(e.target.value)}/></div><nav><button onClick={()=>setTab("sell")}><Icon name="plus"/>Jual Barang</button><button onClick={()=>setTab("activity")}><Icon name="bell"/>{offers.length>0&&<i/>}</button><button onClick={()=>setTab("profile")} className="avatar">{profile.display_name.slice(0,2).toUpperCase()}</button></nav></div></header>
    {(error||message)&&<div className={`toast ${error?"bad":"good"}`}><span>{error||message}</span><button onClick={clear}><Icon name="close" size={17}/></button></div>}
    {tab==="home"&&<section className="page"><div className="mobile-title"><p><Icon name="pin" size={15}/> {profile.area}</p><h1>Barang nyata<br/><em>dekat kamu.</em></h1></div><div className="mobile-search"><Icon name="search"/><input placeholder="Cari barang di sekitar…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chips"><button className={category==="Semua"?"active":""} onClick={()=>setCategory("Semua")}>Semua</button>{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="heading"><div><p>PASAR {profile.area.toUpperCase()}</p><h1>Barang terbaru di sekitar</h1></div><span>{visible.length} barang aktif</span></div>{visible.length===0?<div className="empty"><div><Icon name="search" size={28}/></div><h2>Belum ada barang di area ini</h2><p>Listing akan muncul setelah pengguna di {profile.area} memasang barang.</p><button className="primary" onClick={()=>setTab("sell")}>Pasang barang pertama</button></div>:<div className="grid">{visible.map(item=><article key={item.id} onClick={()=>setSelected(item)}><div className="photo">{item.listing_media[0]?<img src={item.listing_media[0].public_url} alt={item.title}/>:<span>Foto tidak tersedia</span>}{item.negotiable&&<b>Bisa Ditawar</b>}</div><div className="card-copy"><strong>{rupiah(item.price)}</strong><h2>{item.title}</h2><p><Icon name="pin" size={14}/>{item.area}</p><small>{item.condition} · {dateTime(item.created_at)}</small></div></article>)}</div>}</section>}
    {tab==="sell"&&<section className="page narrow"><div className="heading"><div><p>JUAL BARANG</p><h1>Pasang barang baru</h1></div></div><form className="panel form" onSubmit={createListing}><FilePicker/><label>Judul<input name="title" minLength={5} maxLength={120} required/></label><label>Deskripsi<textarea name="description" minLength={10} maxLength={4000} rows={5} required/></label><div className="two"><label>Harga<input name="price" type="number" min="1" required/></label><label>Radius penemuan<CustomSelect name="radius" defaultValue="10" options={[{value:"5",label:"5 km"},{value:"10",label:"10 km"},{value:"25",label:"25 km"},{value:"50",label:"50 km"}]}/></label></div><div className="two"><label>Kategori<CustomSelect name="category" defaultValue={categories[0]} options={categories.map(value=>({value,label:value}))}/></label><label>Kondisi<CustomSelect name="condition" defaultValue={conditions[0]} options={conditions.map(value=>({value,label:value}))}/></label></div><ToggleField name="negotiable" label="Harga bisa ditawar maksimal tiga kali"/><div className="safety"><Icon name="shield"/><span><strong>Pembayaran wajib COD</strong><small>Kontak dan lokasi presisi tidak ditampilkan sebelum deal.</small></span></div><button className="primary" disabled={submitting}>{submitting?"Memasang…":"Pasang barang"}</button></form></section>}
    {tab==="activity"&&<section className="page"><div className="heading"><div><p>AKTIVITAS</p><h1>Tawaran dan Deal Room</h1></div></div><div className="activity-layout"><section><h2>Tawaran masuk <span>{offers.length}</span></h2>{offers.length===0?<div className="mini-empty">Belum ada tawaran yang menunggu jawaban.</div>:offers.map(o=><article className="offer" key={o.id}><div><small>Tawaran {o.attempt_number}/3 · {dateTime(o.created_at)}</small><h3>{o.listing.title}</h3><p>{o.buyer.display_name} · {o.buyer.completed_deals} COD selesai</p></div><strong>{rupiah(o.amount)}</strong><div><button onClick={()=>respond(o.id,"reject")}>Tolak</button><button className="primary" onClick={()=>respond(o.id,"accept")}>Terima</button></div></article>)}</section><section><h2>Deal aktif <span>{deals.filter(d=>d.status!=="completed"&&d.status!=="cancelled").length}</span></h2>{deals.length===0?<div className="mini-empty">Deal Room dibuat otomatis setelah tawaran diterima.</div>:deals.map(d=><DealRoom key={d.id} deal={d} userId={user.id} busy={submitting} onPropose={proposeSchedule} onAccept={acceptSchedule} onConfirm={confirmDeal}/>)}</section></div></section>}
    {tab==="profile"&&<section className="page narrow"><div className="heading"><div><p>PROFIL</p><h1>{profile.display_name}</h1></div></div><div className="panel profile"><div className="profile-avatar">{profile.display_name.slice(0,2).toUpperCase()}</div><div><strong>{profile.area}</strong><p>{profile.completed_deals} COD selesai · {profile.no_shows} no-show</p><small>Bergabung {new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(profile.created_at))}</small></div><button onClick={()=>supabase.auth.signOut()}><Icon name="logout"/>Keluar</button></div></section>}
    {selected&&<div className="overlay" role="dialog" aria-modal="true" aria-label={selected.title}><section className="detail"><button className="close" onClick={()=>setSelected(null)}><Icon name="close"/></button><div className="detail-photo">{selected.listing_media[0]&&<img src={selected.listing_media[0].public_url} alt={selected.title}/>}</div><div className="detail-body"><div className="price-line"><strong>{rupiah(selected.price)}</strong>{selected.negotiable&&<span>Bisa Ditawar</span>}</div><h1>{selected.title}</h1><p className="location"><Icon name="pin" size={16}/>{selected.area}</p><div className="facts"><span><small>Kondisi</small><strong>{selected.condition}</strong></span><span><small>Radius</small><strong>{selected.visibility_radius_km} km</strong></span><span><small>Dipasang</small><strong>{dateTime(selected.created_at)}</strong></span></div><h3>Deskripsi</h3><p className="description">{selected.description}</p><div className="seller"><div className="avatar">{selected.seller.display_name.slice(0,2).toUpperCase()}</div><span><strong>{selected.seller.display_name}</strong><small>{selected.seller.completed_deals} COD selesai · {selected.seller.no_shows} no-show</small></span></div><div className="safety"><Icon name="shield"/><span><strong>Kontak tetap privat sebelum deal</strong><small>Bayar saat bertemu setelah barang diperiksa.</small></span></div>{selected.seller_id!==user.id&&selected.negotiable&&<div className="offer-box"><label>Nominal tawaran<input value={offerAmount} onChange={e=>setOfferAmount(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="Masukkan harga"/></label><button className="primary" disabled={submitting||!offerAmount} onClick={submitOffer}>Kirim tawaran</button><small>Maksimal tiga tawaran untuk listing ini.</small></div>}</div></section></div>}
    <nav className="bottom"><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Icon name="search"/><span>Beranda</span></button><button className={tab==="sell"?"active":""} onClick={()=>setTab("sell")}><Icon name="plus"/><span>Jual</span></button><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}><Icon name="bell"/><span>Aktivitas</span></button><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><Icon name="user"/><span>Profil</span></button></nav>
  </main>
}

function DealRoom({deal,userId,busy,onPropose,onAccept,onConfirm}:{deal:Deal;userId:string;busy:boolean;onPropose:(e:FormEvent<HTMLFormElement>,id:string)=>void;onAccept:(id:string)=>void;onConfirm:(id:string)=>void}){
  const schedule=deal.cod_schedules?.[0]; const other=deal.buyer_id===userId?deal.seller:deal.buyer; const confirmed=deal.deal_confirmations?.some(c=>c.user_id===userId);
  return <article className="deal"><div className="deal-top"><div><small>{deal.status.replaceAll("_"," ").toUpperCase()}</small><h3>{deal.listing.title}</h3><p>COD dengan {other.display_name}</p></div><strong>{rupiah(deal.final_price)}</strong></div>{schedule?<div className="schedule"><p><strong>{dateTime(schedule.scheduled_at)}</strong><span>{schedule.location_name}</span><small>{schedule.location_address}</small></p>{schedule.status==="proposed"&&schedule.proposed_by!==userId&&<button className="primary" disabled={busy} onClick={()=>onAccept(deal.id)}>Setujui jadwal</button>}{schedule.status==="proposed"&&schedule.proposed_by===userId&&<em>Menunggu persetujuan pihak lain</em>}</div>:<form className="schedule-form" onSubmit={e=>onPropose(e,deal.id)}><h4>Usulkan jadwal COD</h4><label>Jadwal WITA<input name="scheduled_at" inputMode="numeric" placeholder="DD/MM/YYYY HH:mm" pattern="\d{2}/\d{2}/\d{4} \d{2}:\d{2}" required/><small>Contoh: 14/08/2026 16:30</small></label><input name="location_name" placeholder="Nama tempat umum" required/><input name="location_address" placeholder="Alamat titik temu" required/><textarea name="notes" placeholder="Catatan pertemuan (opsional)"/><button className="primary" disabled={busy}>Kirim usulan</button></form>}{deal.status==="scheduled"&&<button className="confirm" disabled={busy||confirmed} onClick={()=>onConfirm(deal.id)}>{confirmed?"Konfirmasi tersimpan":deal.buyer_id===userId?"Barang sudah diterima":"Barang sudah diserahkan"}</button>}{deal.status==="completed"&&<div className="completed"><Icon name="check"/>COD selesai oleh kedua pihak</div>}</article>
}
